name: Automation tests
on: workflow_dispatch

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code on runner
        uses: actions/checkout@v3
        
      - name: Run tests
        run: mvn clean test
        
      - name: Generate report
        run: mvn allure::report
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/allure-report'
          retention-days: 30
      - name: Deploy GitHub Pages site
      
        uses: actions/deploy-pages@v2
