name: Automation tests
on: workflow_dispatch

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code on runner
        uses: actions/checkout@v3
        
      - name: Run tests
        run: mvn clean test
        
      - name: Generate report
        run: mvn allure::report
        
      - name: Create a temp folder for allure history
        run: mkdir allure-history-temp
      
      - name: Download artifact (allure history folder) 
        uses: actions/download-artifact@v3
        with:
          name: allure-history-folder
          path: target/allure-report/history
          
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/allure-report'
          retention-days: 30
          if-no-files-found: ignore
          
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2
