name: Automation tests
on: 
  workflow_dispatch:
    inputs:
      suite:
        type: choice
        description: Name of xml suite
        options: 
          - regression
          - smoke
          - integration
      environment:
        type: choice
        description: Profile
        options: 
          - dev
          - stage
          - test

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code on runner
        uses: actions/checkout@v3
        
      - name: Run tests
        run: mvn clean test -Dsuite=${{ github.event.inputs.suite }} -P ${{ github.event.inputs.environment }}
        
      - name: Create a temp folder for allure history
        run: mkdir allure-history-temp
        
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: maven.yml
          name: allure-history-artifact
          path: allure-history-temp
          if_no_artifact_found: warn
        
      - name: Extract artifact
        continue-on-error: true
        run: | 
          cd allure-history-temp
          tar -xf artifact.tar
          
      - name: Move history folder to allure-results
        run: |
          mkdir target/allure-results/history/
          mv allure-history-temp/history/* target/allure-results/history/
        
      - name: Generate report
        run: mvn allure::report
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: allure-history-artifact
          path: 'target/allure-report'
          retention-days: 30
          
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2
        with:
          artifact_name: allure-history-artifact
