name: Automation tests
on: workflow_dispatch

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code on runner
        uses: actions/checkout@v3
        
      - name: Run tests
        run: mvn clean test
        
      - name: Create a temp folder for allure history
        run: mkdir allure-history-temp
        
      - name: Print all files
        run: ls -R
        
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: maven.yml
          name: allure-history-artifact
          path: allure-history-temp
          if_no_artifact_found: warn
      
      - name: Print all files
        run: ls -R
        
      - name: Generate report
        run: mvn allure::report
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: allure-history-artifact
          path: 'target/allure-report'
          retention-days: 30
          
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2
        with:
          artifact_name: allure-history-artifact
