name: Automation tests
on: 
  workflow_dispatch:
    inputs:
      suite:
        type: choice
        description: Name of xml suite
        options: 
          - regression
          - smoke
          - integration
      environment:
        type: choice
        description: Profile
        options: 
          - dev
          - stage
          - test

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code on runner
        uses: actions/checkout@v3
        
      - name: Cache maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: mavem-dependencies-${{ hashFiles('**/pom.xml') }}
        
      - name: Create property files
        run: |
          mkdir src/main/resources/env
          cd src/main/resources/env && touch dev-config.properties && touch stage-config.properties && touch test-config.properties
      
      - name: Get properties for dev
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: |
          cat > src/main/resources/env/dev-config.properties << EOF
          ${{ secrets.SECRETS_DEV }}
          EOF
          
      - name: Get properties for stage
        if: ${{ github.event.inputs.environment == 'stage' }}
        run: |
          cat > src/main/resources/env/stage-config.properties << EOF
          ${{ secrets.SECRETS_STAGE }}
          EOF
          
      - name: Get properties for test
        if: ${{ github.event.inputs.environment == 'test' }}
        run: |
          cat > src/main/resources/env/test-config.properties << EOF
          ${{ secrets.SECRETS_TEST }}
          EOF
      
      - name: Run tests
        run: mvn clean test -Dsuite=${{ github.event.inputs.suite }}.xml -P ${{ github.event.inputs.environment }}
        
      - name: Create a temp folder for allure history
        run: mkdir allure-history-temp
        
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: maven.yml
          name: allure-history-artifact
          path: allure-history-temp
          if_no_artifact_found: warn
        
      - name: Extract artifact
        continue-on-error: true
        run: | 
          cd allure-history-temp
          tar -xf artifact.tar
          
      - name: Move history folder to allure-results
        run: |
          mkdir target/allure-results/history/
          mv allure-history-temp/history/* target/allure-results/history/
          
      - name: Create environemnt properties file for allure report
        run: |
          cat > target/allure-results/environment.properties << EOF
          SERVER=${{ github.event.inputs.environment }}
          EOF
        
      - name: Generate report
        run: mvn allure::report
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: allure-history-artifact
          path: 'target/allure-report'
          retention-days: 30
          
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2
        with:
          artifact_name: allure-history-artifact
